CREATE VIEW CustomerLifetimeValue AS
SELECT
    c.id AS customer_id,
    CONCAT(CONVERT(NVARCHAR(MAX), c.last_name), ', ', CONVERT(NVARCHAR(MAX), c.first_name)) AS customer_name,
    CAST(c.email AS NVARCHAR(MAX)) AS email,
    COUNT(o.id) AS total_orders, -- Total number of orders per customer
    SUM(o.total_price) AS total_revenue, -- Total revenue generated by the customer
    AVG(o.total_price) AS avg_order_value, -- Average order value for the customer
    DATEDIFF(DAY, MIN(o.created_at), GETDATE()) AS customer_tenure_days, -- Customer tenure from first order to today
    -- CLV estimation based on average revenue per order and customer tenure
    (AVG(o.total_price) * COUNT(o.id)) AS estimated_clv -- Simplified CLV: avg revenue per order * total orders
FROM 
    customers c
JOIN 
    orders o ON c.id = o.customer_id
GROUP BY 
    c.id, 
    CONVERT(NVARCHAR(MAX), c.last_name), 
    CONVERT(NVARCHAR(MAX), c.first_name), 
    CAST(c.email AS NVARCHAR(MAX));